# default_install_hook_types :["pre-commit", "coomit-msg", "pre-push"]

repos:
-   repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: mypy
        language: system
        types: [python]
        verbose: true
        args:
          - --show-error-codes
          - --config-file
          - pyproject.toml

      - id: interrogate
        name: interrogate
        entry: interrogate
        language: system
        types: [python]
        args:
          - --fail-under=80
          - --verbose

-   repo: local
    hooks:
      - id: ruff format
        name: Ruff format
        entry: ruff format
        language: system
        types: [python]

-   repo: local
    hooks:
      - id: ruff
        name: Ruff Linter
        entry: ruff check
        language: system
        types: [python]
        args: [--fix, --show-fixes, --exit-non-zero-on-fix]

# -   repo: https://
#     rev:
#     hooks:
#     - id: trailing-whitespace

